"""
Core data models for supply chain entities.
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Dict, Optional
from enum import Enum


class DisruptionSeverity(Enum):
    """Severity levels for supply chain disruptions."""
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4


class DisruptionType(Enum):
    """Types of supply chain disruptions."""
    GEOPOLITICAL = "geopolitical"
    WEATHER = "weather"
    SUPPLIER_FAILURE = "supplier_failure"
    LOGISTICS = "logistics"
    DEMAND_SPIKE = "demand_spike"
    QUALITY_ISSUE = "quality_issue"


class SupplierStatus(Enum):
    """Status of suppliers in the network."""
    ACTIVE = "active"
    AT_RISK = "at_risk"
    DISRUPTED = "disrupted"
    OFFLINE = "offline"


@dataclass
class Location:
    """Geographic location."""
    country: str
    region: str
    city: str
    latitude: float
    longitude: float


@dataclass
class Supplier:
    """Supplier entity in supply chain."""
    id: str
    name: str
    location: Location
    status: SupplierStatus
    reliability_score: float  # 0-100
    lead_time_days: int
    capacity: int
    products: List[str]
    risk_factors: List[str] = field(default_factory=list)
    
    def to_dict(self) -> Dict:
        return {
            'id': self.id,
            'name': self.name,
            'location': {
                'country': self.location.country,
                'region': self.location.region,
                'city': self.location.city,
                'latitude': self.location.latitude,
                'longitude': self.location.longitude
            },
            'status': self.status.value,
            'reliability_score': self.reliability_score,
            'lead_time_days': self.lead_time_days,
            'capacity': self.capacity,
            'products': self.products,
            'risk_factors': self.risk_factors
        }


@dataclass
class Route:
    """Transportation route between locations."""
    id: str
    origin: Location
    destination: Location
    transport_mode: str  # air, sea, land, rail
    distance_km: float
    avg_duration_hours: float
    cost_per_unit: float
    reliability_score: float  # 0-100
    status: str = "operational"


@dataclass
class Disruption:
    """Supply chain disruption event."""
    id: str
    type: DisruptionType
    severity: DisruptionSeverity
    location: Location
    description: str
    start_time: datetime
    end_time: Optional[datetime]
    affected_suppliers: List[str]
    affected_routes: List[str]
    predicted_impact_score: float  # 0-100
    source: str  # news, sensor, manual, etc.
    
    def is_active(self) -> bool:
        """Check if disruption is currently active."""
        if self.end_time is None:
            return True
        return datetime.now() < self.end_time
    
    def to_dict(self) -> Dict:
        return {
            'id': self.id,
            'type': self.type.value,
            'severity': self.severity.value,
            'location': {
                'country': self.location.country,
                'region': self.location.region,
                'city': self.location.city
            },
            'description': self.description,
            'start_time': self.start_time.isoformat(),
            'end_time': self.end_time.isoformat() if self.end_time else None,
            'affected_suppliers': self.affected_suppliers,
            'affected_routes': self.affected_routes,
            'predicted_impact_score': self.predicted_impact_score,
            'source': self.source,
            'is_active': self.is_active()
        }


@dataclass
class Alert:
    """Crisis alert generated by the system."""
    id: str
    timestamp: datetime
    disruption_id: str
    severity: DisruptionSeverity
    title: str
    message: str
    recommended_actions: List[str]
    affected_entities: Dict[str, List[str]]  # suppliers, routes, products
    estimated_financial_impact: float  # in USD
    
    def to_dict(self) -> Dict:
        return {
            'id': self.id,
            'timestamp': self.timestamp.isoformat(),
            'disruption_id': self.disruption_id,
            'severity': self.severity.value,
            'title': self.title,
            'message': self.message,
            'recommended_actions': self.recommended_actions,
            'affected_entities': self.affected_entities,
            'estimated_financial_impact': self.estimated_financial_impact
        }


@dataclass
class ResponsePlan:
    """Automated response plan for a disruption."""
    id: str
    disruption_id: str
    created_at: datetime
    priority: int  # 1-5, 5 being highest
    alternative_suppliers: List[Dict]
    alternative_routes: List[Dict]
    inventory_adjustments: Dict[str, int]
    estimated_cost: float
    estimated_time_to_resolve: int  # in hours
    confidence_score: float  # 0-100
    
    def to_dict(self) -> Dict:
        return {
            'id': self.id,
            'disruption_id': self.disruption_id,
            'created_at': self.created_at.isoformat(),
            'priority': self.priority,
            'alternative_suppliers': self.alternative_suppliers,
            'alternative_routes': self.alternative_routes,
            'inventory_adjustments': self.inventory_adjustments,
            'estimated_cost': self.estimated_cost,
            'estimated_time_to_resolve': self.estimated_time_to_resolve,
            'confidence_score': self.confidence_score
        }
